### PR TITLE
use -fwrite-if-simplified-core to avoid unused bytecode generation

### PR DESCRIPTION
**Pull request by tek**
We can't do anything with the target's bytecode during its compilation session, so the simpler flag is sufficient.

### CODE REVIEW

**Comment by wavewave** [comment]
oh. is this enough? In cabal-based build, without `-fbyte-code-and-object-code`,  I remember the build did not work, but that is likely to be a `ghc --make` issue. I will try it on the big repo and let you know about the result. Thanks!

**Comment by tek** [comment]
In make mode, the bytecode generated after compilation is stored in the HUG, while it's discarded in oneshot mode.

Although you'd expect make mode to fall back to interface-loaded bytecode, but I assume that's avoided because you can just get it directly with `-fbyte-code-and-object-code`. However, even then it generates bytecode unnecessarily for all the modules that aren't used by TH downstream!

**Comment by wavewave** [comment]
Got it. yes. there is no reason why we need to run `initWholeCoreBinding` at the time of the module compilation. In the philosophy of serialized Core in hi file, the byte code should be generated on the fly at the use site of the module in TH, and `ghc --make` does it implicitly using lazy calls. 
I tested this with the big repo and didn't have any regression (the benefit is also undetectable, but that's because the repo uses TH so extensively, I think). The change is much clearer in the meaning. Thanks!

**Review by wavewave — APPROVED** [review]

**Comment by tek** [comment]
yeah, I tried briefly to benchmark a contrived test project but didn't notice a difference either. I'm pretty certain I verified that the flag isn't force-enabled by GHC, but I'll double check. Otherwise it appears that compiling to bytecode is just so cheap compared to typechecking and compiling to STG that it doesn't matter. I guess we should see that on a speedscope graph...

**Pull request merged**
